apiVersion: v2
name: sealed-secrets
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: sealed-secrets
  version: 2.1.4
  repository: https://bitnami-labs.github.io/sealed-secrets/