apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-operator-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: 'https://github.com/younesELouafi/argo-helm'
    path: Infrastructure/operators
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: milvus-operator-ns
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true